<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-26T18:18:32 IST" name="Default suite" finished-at="2021-10-26T18:19:04 IST" duration-ms="32053">
    <groups>
    </groups>
    <test started-at="2021-10-26T18:18:32 IST" name="Default test" finished-at="2021-10-26T18:19:04 IST" duration-ms="32053">
      <class name="vtiger.Tc_001_CreateContact_org_Test">
        <test-method is-config="true" signature="startconnection()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:18:32 IST" name="startconnection" finished-at="2021-10-26T18:18:32 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startconnection -->
        <test-method is-config="true" signature="launchbrowser()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:18:32 IST" name="launchbrowser" finished-at="2021-10-26T18:18:37 IST" duration-ms="4827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchbrowser -->
        <test-method is-config="true" signature="logindetails()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:18:37 IST" name="logindetails" finished-at="2021-10-26T18:18:42 IST" duration-ms="5415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindetails -->
        <test-method signature="CreatecontactTest()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:18:42 IST" name="CreatecontactTest" finished-at="2021-10-26T18:19:01 IST" duration-ms="18700" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at vtiger.Tc_001_CreateContact_org_Test.CreatecontactTest(Tc_001_CreateContact_org_Test.java:82)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatecontactTest -->
        <test-method is-config="true" signature="logout()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:19:01 IST" name="logout" finished-at="2021-10-26T18:19:03 IST" duration-ms="2482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:19:03 IST" name="closebrowser" finished-at="2021-10-26T18:19:04 IST" duration-ms="108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="closeconnection()[pri:0, instance:vtiger.Tc_001_CreateContact_org_Test@2e385cce]" started-at="2021-10-26T18:19:04 IST" name="closeconnection" finished-at="2021-10-26T18:19:04 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeconnection -->
      </class> <!-- vtiger.Tc_001_CreateContact_org_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
